Update start script for influxdb

diff --git a/influxdb/scripts/start-stop-status b/influxdb/scripts/start-stop-status
--- a/influxdb/scripts/start-stop-status
+++ b/influxdb/scripts/start-stop-status
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-# Copyright (c) 2017, James Bowen, All Rights Reserved
+# Copyright (c) 2019, James Bowen, All Rights Reserved
 
-# Based on init.sh from influxdb-1.3.4
+# Based on init.sh from influxdb-1.3.4 and start-stop-status from spksrc
 
 # Daemon options
 INFLUXD_OPTS=
@@ -39,177 +39,157 @@ fi
 CONFIG=${PKG_DIR}/etc/influxdb.conf
 
 # PID file for the daemon
-PIDFILE=/var/run/${NAME}/$(basename ${DAEMON}).pid
-PIDDIR=`dirname $PIDFILE`
-if [ ! -d "$PIDDIR" ]; then
-    mkdir -p $PIDDIR
-    chown $USER:$GROUP $PIDDIR
+PID_FILE=/var/run/${NAME}/$(basename ${DAEMON}).pid
+PID_DIR=`dirname $PID_FILE`
+if [ ! -d "$PID_DIR" ]; then
+    mkdir -p $PID_DIR
 fi
+chown $USER:$GROUP $PID_DIR
 
 # Max open files
 OPEN_FILE_LIMIT=65536
 
 # Logging
-if [ -z "$STDOUT" ]; then
-    STDOUT=/dev/null
+if [ ! -f "$LOG_FILE" ]; then
+    mkdir -p $(dirname $LOG_FILE)
+    chown $USER:$GROUP $(dirname $LOG_FILE)
+    touch $LOG_FILE
 fi
+chown $USER:$GROUP $LOG_FILE
 
-if [ ! -f "$STDOUT" ]; then
-    mkdir -p $(dirname $STDOUT)
-fi
+error() {
+    rc=$1
+    msg=$2
 
-if [ -z "$STDERR" ]; then
-    STDERR=${LOG_FILE}
-fi
-
-if [ ! -f "$STDERR" ]; then
-    mkdir -p $(dirname $STDERR)
-    chown $USER:$GROUP $(dirname $STDERR)
-fi
-
-function log_failure_msg() {
-    echo "$@" "[ FAILED ]"
-}
-
-function log_success_msg() {
-    echo "$@" "[ OK ]"
-}
-
-function start() {
-    # Check if config file exist
-    if [ ! -r $CONFIG ]; then
-        log_failure_msg "config file $CONFIG doesn't exist (or you don't have permission to view)"
-        exit 4
+    if [ -n "$SYNOPKG_TEMP_LOGFILE" ]; then
+        echo "ERROR: $msg" >> $SYNOPKG_TEMP_LOGFILE
     fi
 
-    # Check that the PID file exists, and check the actual status of process
-    if [ -f $PIDFILE ]; then
-        PID="$(cat $PIDFILE)"
-        if kill -0 "$PID" &>/dev/null; then
-            # Process is already up
-            log_success_msg "$NAME process is already running"
-            return 0
-        fi
-    else
-        su -s /bin/sh -c "touch $PIDFILE" $USER &>/dev/null
-        if [ $? -ne 0 ]; then
-            log_failure_msg "$PIDFILE not writable, check permissions"
-            exit 5
-        fi
+    echo "ERROR: $msg" >&2
+    exit $rc
+}
+
+start_daemon() {
+    echo "Starting $NAME" >> $LOG_FILE
+
+    # Check if config file exist
+    if [ ! -r $CONFIG ]; then
+        error 4 "Config file $CONFIG doesn't exist (or you don't have permission to view)"
+    fi
+
+    # Check that the PID file is writeable
+    su -s /bin/sh -c "touch $PID_FILE" $USER &>/dev/null
+    if [ $? -ne 0 ]; then
+        error 5 "$PID_FILE not writable, check permissions"
     fi
 
     # Bump the file limits, before launching the daemon. These will
     # carry over to launched processes.
     ulimit -n $OPEN_FILE_LIMIT
     if [ $? -ne 0 ]; then
-        log_failure_msg "Unable to set ulimit to $OPEN_FILE_LIMIT"
-        exit 1
+        error 1 "Unable to set ulimit to $OPEN_FILE_LIMIT"
     fi
 
     # Launch process
-    echo "Starting $NAME..."
-    if which start-stop-daemon &>/dev/null; then
-        start-stop-daemon \
-            --chuid $USER:$GROUP \
-            --start \
-            --quiet \
-            --pidfile $PIDFILE \
-            --exec $DAEMON \
-            -- \
-            -pidfile $PIDFILE \
-            -config $CONFIG \
-            $INFLUXD_OPTS >>$STDOUT 2>>$STDERR &
-    else
-        local CMD="$DAEMON -pidfile $PIDFILE -config $CONFIG $INFLUXD_OPTS >>$STDOUT 2>>$STDERR &"
-        su -s /bin/sh -c "$CMD" $USER
-    fi
+    local CMD="$DAEMON -pidfile $PID_FILE -config $CONFIG $INFLUXD_OPTS >>/dev/null 2>>$LOG_FILE &"
+    su -s /bin/sh -c "$CMD" $USER
 
-    # Sleep to verify process is still up
-    sleep 5
-    if [ -f $PIDFILE ]; then
-        # PIDFILE exists
-        if kill -0 $(cat $PIDFILE) &>/dev/null; then
-            # PID up, service running
-            log_success_msg "$NAME process was started"
-            return 0
-        else
-            rm $PIDFILE
-        fi
+    wait_for_status 0
+    if [ $? -ne 0 ]; then
+        error 1 "Unable to start $NAME. Timeout exceeded."
     fi
-    log_failure_msg "$NAME process was unable to start"
-    exit 1
 }
 
-function stop() {
+
+stop_daemon() {
+
     # Stop the daemon.
-    if [ -f $PIDFILE ]; then
-        local PID="$(cat $PIDFILE)"
-        if kill -0 $PID &>/dev/null; then
-            echo "Stopping $NAME..."
-            # Process still up, send SIGTERM and remove PIDFILE
-            kill -s TERM $PID &>/dev/null && rm -f "$PIDFILE" &>/dev/null
-            n=0
-            while true; do
-                # Enter loop to ensure process is stopped
-                kill -0 $PID &>/dev/null
-                if [ "$?" != "0" ]; then
-                    # Process stopped, break from loop
-                    log_success_msg "$NAME process was stopped"
-                    return 0
-                fi
+    if [ -f $PID_FILE ]; then
+        local PID="$(cat $PID_FILE)"
 
-                # Process still up after signal, sleep and wait
-                sleep 1
-                n=$(expr $n + 1)
-                if [ $n -eq 30 ]; then
-                    # After 30 seconds, send SIGKILL
-                    echo "Timeout exceeded, sending SIGKILL..."
-                    kill -s KILL $PID &>/dev/null
-                elif [ $? -eq 40 ]; then
-                    # After 40 seconds, error out
-                    log_failure_msg "could not stop $NAME process"
-                    exit 1
-                fi
-            done
+        echo "Stopping $NAME" >> $LOG_FILE
+        kill -TERM $PID >> $LOG_FILE 2>&1
+
+        wait_for_status 1
+        if [ $? -ne 0 ]; then
+            kill -KILL $PID >> $LOG_FILE 2>&1
+
+            wait_for_status 1 5
+            if [ $? -ne 0 ]; then
+                error 1 "Unable to stop $NAME. Timeout exceeded."
+            fi
+        fi
+
+        if [ -f "$PID_FILE" ]; then
+            rm -f "$PID_FILE" &> /dev/null
         fi
     fi
-    log_success_msg "$NAME process already stopped"
 }
 
-function restart() {
+restart() {
     # Restart the daemon.
     stop
     start
 }
 
-function status() {
-    # Check the status of the process.
-    if [ -f $PIDFILE ]; then
-        PID="$(cat $PIDFILE)"
-        if kill -0 $PID &>/dev/null; then
-            log_success_msg "$NAME process is running"
-            exit 0
-        else
-            # PID file present but no matching process
-            log_failure_msg "$NAME process is not running (stale PID file)"
-            exit 1
-        fi
-    fi
-    log_failure_msg "$NAME process is not running"
-    exit 3
+log() {
+    echo ${LOG_FILE}
 }
 
-function log() {
-    echo ${LOG_FILE}
+daemon_status() {
+    if [ -n "${PID_FILE}" -a -r "${PID_FILE}" ]; then
+        if kill -0 $(cat "${PID_FILE}") > /dev/null 2>&1; then
+            return
+        fi
+        rm -f "${PID_FILE}" > /dev/null
+    fi
+    return 1
+}
+
+wait_for_status() {
+    timeout=$2
+    # default value: 20 seconds
+    counter=${timeout:=20}
+    while [ ${counter} -gt 0 ]; do
+        daemon_status
+        [ $? -eq $1 ] && return
+        counter=$((counter-1))
+        sleep 1
+    done
+    return 1
 }
 
 case $1 in
     start)
-        start
+        if daemon_status; then
+            echo "${NAME} is already running"
+            exit 0
+        else
+            echo "Starting ${NAME} ..."
+            start_daemon
+            exit $?
+        fi
         ;;
 
     stop)
-        stop
+        if daemon_status; then
+            echo "Stopping ${NAME} ..."
+            stop_daemon
+            exit $?
+        else
+            echo "${NAME} is not running"
+            exit 0
+        fi
+        ;;
+
+    status)
+        if daemon_status; then
+            echo "${NAME} is running"
+            exit 0
+        else
+            echo "${NAME} is not running"
+            exit 3
+        fi
         ;;
 
     restart)
